<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite hostname="Youngs-MacBook-Pro.local" name="main.java.com.dbyl.appiumCore.tests.iOSWebBrowser" tests="1" failures="0" timestamp="9 Sep 2016 13:22:29 GMT" time="0.001" errors="1">
  <testcase name="runWebBrowser" time="0.001" classname="main.java.com.dbyl.appiumCore.tests.iOSWebBrowser">
    <error type="java.lang.NullPointerException" message="while trying to invoke the method io.appium.java_client.ios.IOSDriver.quit() of a null object loaded from field main.java.com.dbyl.appiumCore.tests.iOSWebBrowser.driver of an object loaded from local variable &#039;this&#039;">
      <![CDATA[java.lang.NullPointerException: while trying to invoke the method io.appium.java_client.ios.IOSDriver.quit() of a null object loaded from field main.java.com.dbyl.appiumCore.tests.iOSWebBrowser.driver of an object loaded from local variable 'this'
	at main.java.com.dbyl.appiumCore.tests.iOSWebBrowser.tearDown(iOSWebBrowser.java:89)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:100)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:515)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:216)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:143)
	at org.testng.internal.TestMethodWorker.invokeAfterClassMethods(TestMethodWorker.java:217)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:115)
	at org.testng.TestRunner.privateRun(TestRunner.java:746)
	at org.testng.TestRunner.run(TestRunner.java:600)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:366)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:361)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:319)
	at org.testng.SuiteRunner.run(SuiteRunner.java:268)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1264)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1189)
	at org.testng.TestNG.runSuites(TestNG.java:1104)
	at org.testng.TestNG.run(TestNG.java:1076)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:126)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:152)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:57)
]]>
    </error>
  </testcase> <!-- runWebBrowser -->
</testsuite> <!-- main.java.com.dbyl.appiumCore.tests.iOSWebBrowser -->
